export const ADD="ADD"
export const SUB="SUB"
export const SWEET="SWEET"
export const CLEAR="CLEAR"
// export const LogInAction="LogInAction"
export const users="users"
export const remove_user="remove_user"